/**
 * @fileoverview electron-builder afterPack hook that wraps the packaged Linux binary in a launcher
 * script which enables Chromium's `--no-sandbox` fallback only when the AppImage runtime has no
 * usable sandbox.
 *
 * Why this exists:
 * - An AppImage runs from an ephemeral, user-owned FUSE mount, so `chrome-sandbox` can never carry
 *   the root-owned setuid bit Chromium's SUID sandbox requires. AppImages have always relied on
 *   the alternative namespace sandbox instead.
 * - Ubuntu 23.10+ sets `kernel.apparmor_restrict_unprivileged_userns=1`, which blocks unprivileged
 *   user namespaces for binaries without an AppArmor profile granting `userns`. An AppImage has no
 *   install step, so it cannot install such a profile (that would require root).
 * - With neither sandbox available Chromium aborts during startup - before `app.whenReady()` - so
 *   this cannot be detected or reported from inside the application. It has to happen in a shell
 *   wrapper that runs before the binary. See https://github.com/electron/electron/issues/41066.
 *
 * electron-builder does put `--no-sandbox` in the AppImage's generated `.desktop` entry, but that
 * only applies to desktop-integrated launches; double-clicking the `.AppImage` invokes `AppRun`
 * directly with no arguments and gets nothing. The launcher closes that gap.
 *
 * Deliberately narrow: the launcher degrades ONLY when running from an AppImage (`$APPIMAGE` set)
 * AND user namespaces are actually unavailable. The same packed output is reused for the .deb and
 * .rpm targets, and there the launcher is a pass-through - those packages install an AppArmor
 * profile in their postinst and keep the sandbox fully enabled.
 *
 * Key exports:
 * - module.exports: the afterPack hook, wired up via `afterPack` in electron-builder-config.cjs
 *
 * @module scripts/linux/after-pack
 */

const fs = require('node:fs');
const path = require('node:path');

/** Must match `executableName` in electron-builder-config.cjs. */
const EXECUTABLE_NAME = 'FlashForgeUI';

/**
 * Name the real Electron binary is moved aside to. The AppArmor profile in
 * assets/linux/apparmor-profile attaches to both this and the launcher; keep them in sync.
 */
const REAL_BINARY_NAME = `${EXECUTABLE_NAME}.bin`;

/**
 * Marker comment used to recognize a launcher this hook already wrote, so repeated packs (or a
 * rebuild over a dirty output directory) do not wrap the wrapper.
 */
const LAUNCHER_MARKER = '# FlashForgeUI sandbox-aware launcher';

const LAUNCHER_SCRIPT = `#!/bin/bash
${LAUNCHER_MARKER}
#
# Generated by scripts/linux/after-pack.cjs - do not edit inside the packaged app.
#
# Chooses between a sandboxed and an unsandboxed launch. See the hook for the full rationale;
# in short, an AppImage on Ubuntu 23.10+ has neither the SUID sandbox (impossible from a FUSE
# mount) nor the namespace sandbox (blocked by AppArmor), and Chromium aborts before the app can
# report anything. Falling back to --no-sandbox there is the difference between the app starting
# and the user seeing nothing happen at all.
set -u

HERE="$(dirname "$(readlink -f "\${0}")")"
BIN="\$HERE/${REAL_BINARY_NAME}"

# Only AppImage launches are eligible for the fallback. Under .deb/.rpm the postinst installs an
# AppArmor profile granting userns and sets up chrome-sandbox, so the sandbox must stay enabled.
if [ -n "\${APPIMAGE:-}" ]; then
  # 'unshare --user true' is the same probe electron-builder's postinst uses. If unshare itself is
  # unavailable we cannot test, so we assume namespaces work and keep the sandbox on rather than
  # silently weakening it.
  if command -v unshare >/dev/null 2>&1; then
    if ! { [ -L /proc/self/ns/user ] && unshare --user true; } >/dev/null 2>&1; then
      exec "\$BIN" --no-sandbox "\$@"
    fi
  fi
fi

exec "\$BIN" "\$@"
`;

/**
 * Wrap the packed Linux executable. No-ops on non-Linux packs and on output directories that have
 * already been wrapped.
 *
 * @param {{ electronPlatformName: string, appOutDir: string }} context - electron-builder afterPack context.
 * @returns {Promise<void>}
 */
module.exports = async function afterPack(context) {
  if (context.electronPlatformName !== 'linux') {
    return;
  }

  const launcherPath = path.join(context.appOutDir, EXECUTABLE_NAME);
  const realBinaryPath = path.join(context.appOutDir, REAL_BINARY_NAME);

  if (fs.existsSync(realBinaryPath)) {
    console.log(`[after-pack] Launcher already present in ${context.appOutDir} - skipping.`);
    return;
  }

  if (!fs.existsSync(launcherPath)) {
    throw new Error(
      `[after-pack] Expected packed executable at ${launcherPath} but it does not exist. ` +
        `Has executableName changed in electron-builder-config.cjs?`
    );
  }

  fs.renameSync(launcherPath, realBinaryPath);
  fs.writeFileSync(launcherPath, LAUNCHER_SCRIPT, { encoding: 'utf8', mode: 0o755 });
  // writeFileSync only applies `mode` when it creates the file; chmod unconditionally so a
  // pre-existing file (or a restrictive umask) cannot leave the launcher non-executable.
  fs.chmodSync(launcherPath, 0o755);

  console.log(`[after-pack] Wrapped ${EXECUTABLE_NAME} with the sandbox-aware launcher.`);
};
